### ISSUE TITLE
Dosyaların imzalanması sırasında bir hata oluştu

### ISSUE THREAD

**Issue by javastud** [mfarkan/E-Imza-iTextSharp-ESYA-Api#1]
Selamlar,

Öncelikle teşekkürler emeğiniz için. .net framework 3.5 kurmadan solution açılmadı. Onu kurduktan sonra hem KamuSM TEST sertifikası ile hem de TurkTrust normal sertifikası ile denedim ancak her ikisinde de SignatureManager:23 satırda aşağıdaki gibi bir çıktı alıyoruz.

"Empty path name is not legal" itext den
Exception thrown: 'System.ArgumentException' in mscorlib.dll
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   **at iTextSharp.text.pdf.PdfStamper.CreateSignature(PdfReader reader, Stream os, Char pdfVersion, String tempFile, Boolean append)**
   at DesktopPdfSigner.PdfSigner.PdfSigner.SignPDF(PdfRequestDTO request, Byte[] PDFContent) in D:\E-Imza-iTextSharp-ESYA-Api\E-DesktopPdfSigner\PdfSigner\PdfSigner.cs:line 74
   at DesktopPdfSigner.SignatureManager.SignatureManager.SignPdf(PdfRequestDTO requestDTO) in D:\E-Imza-iTextSharp-ESYA-Api\E-DesktopPdfSigner\SignatureManager\SignatureManager.cs:line 18

**Comment by mfarkan** [comment]
merhaba , ben teşekkür ederim.Uygulamanın frameworkü konusunu tekrar kontrol etmem gerekebilir.Eğer uygulama 3.5 ver fakat aldığınız hata aslında **SignPDF methodunun  23.satırında değil de içerisinde.** Şuanda elimde herhangi bir imza aracı mevcut değil hata üstünden gitmek gerekiyor.

Ayrıca bu uygulamanın C:\\ klasörüne yazma yetkisi olup olmadığını kontrol edebilir misiniz ? arattığımda dosya yazma işlemiyle ilgili bir sorun olduğunu tahmin ediyorum isterseniz uygulamanın altına bir klasöre PDF imzalatmayı deneyebilir misiniz ?

**Comment by javastud** [comment]
Merhaba,

Sorun dediğiniz gibi 74 satırını aşağıdaki şekilde değiştirince düzeldi.

PdfStamper pdfStamper = PdfStamper.CreateSignature(pdfReader, stream, '\0', **null**, true);

Bu uygulamaya XML signing eklemek mümkün mü? Önerebileceğiniz bir doküman var mıdır?

**Comment by mfarkan** [comment]
Teşekkürler , sanırım şuanda imzalama işlemini yaptınız diye algılıyorum.Bu arada itextSharpı ve Windows Uygulamasının frameworkünü güncelleyerek deneyebilirsiniz güncel framework iyidir.

Ayrıca benim zamanım kısıtlı olduğu için sadece PDF imzalama işlemlerine bakabildim , fakat tek yararlandığım kaynak buydu ; 

[KAMU SM](https://yazilim.kamusm.gov.tr/esya-api/doku.php)

Sanırım issue'yu kapatabilirsiniz 👍

**Comment by javastud** [comment]
Ayrıca 
70.nci satırı aşağıdaki gibi değiştirince deprecated hatası da gitti.
ocsp = new OcspClientBouncyCastle(**null**);

**Comment by mfarkan** [comment]
Çok teşekkürler , gerekli değişiklikleri yaptığınız için teşekkür ederim.Kamu SM'in dökümantasyonunda xml imzalama ile ilgili (özellikle e-fatura) kısımlar mevcut yardımcı olur diye düşünüyorum.

İyi günler dilerim 👍

**Comment by enginhazar** [comment]
Merhabalar
Bu proje ile imzalanan PDF dosyaları imzager ile doğrulanmıyor bilginiz varmı
